# Generated by Django 4.2.25 on 2026-04-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
