# Generated by Django 4.2.25 on 2026-04-17 06:31

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routes_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="gpx_file",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="route",
            name="map_center_lat",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("-90.000000")),
                    django.core.validators.MaxValueValidator(Decimal("90.000000")),
                ],
            ),
        ),
        migrations.AddField(
            model_name="route",
            name="map_center_lng",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("-180.000000")),
                    django.core.validators.MaxValueValidator(Decimal("180.000000")),
                ],
            ),
        ),
        migrations.AddField(
            model_name="route",
            name="map_zoom",
            field=models.PositiveSmallIntegerField(
                default=12,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(18),
                ],
            ),
        ),
    ]
