# Generated by Django 4.2.25 on 2026-04-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routes_app", "0002_route_gpx_file_route_map_center_lat_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="route",
            name="card_image",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="route",
            name="hero_image",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
