# Generated by Django 4.2.25 on 2026-05-10 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routes_app", "0003_alter_route_card_image_alter_route_hero_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guide",
            name="profile_image",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
